name: tests
on:
  push:
    paths:
      - src
      - tests
  pull_request:
    paths:
      - src
      - tests

jobs:
  build:
    name: Code_Quality
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: [7.2, 7.3, 7.4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@a507be7
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: 'xdebug'
      - name: Composer Install
        run: composer install -o
      - name: Tests
        run: 'composer psalm && composer test'
